all: sim_part1 sim_part2

sim_part1: src/simulator_part1.cpp
	g++ -std=c++17 src/simulator_part1.cpp -o sim_part1

sim_part2: src/simulator_part2.cpp
	g++ -std=c++17 src/simulator_part2.cpp -o sim_part2

clean:
	rm -f sim_part1 sim_part2
